baseURL: "https://ovlasovets.netlify.app"
languageCode: "en-us"
title: "Oleg Vlasovets"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Oleg Vlasovets"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Oleg Vlasovets" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
#    intro: "Hi, my name is"
    title: "Oleg Vlasovets"
    subtitle: "Data Scientist / Guitarist"
    content: "Currently studying bacteria in the human's gut."
    image: /images/guitar.png
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: https://www.dropbox.com/s/1njoi79hcozw7h5/1CV_Vlasovets.pdf?dl=0
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Vlasovets
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ovlasovets/
        - icon: fab fa-twitter
          url: https://twitter.com/ovlasovets

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/only_face.png
    content: |-
      I'm a data scientist who is fascinated by microbes and their impact on human health. I 
      develop methods for describing this link and build open-source software that assists 
      researchers all over the world in performing cutting-edge microbiome data analysis.
    skills:
      enable: true
      title: "Core competences:"
      items:
        - "Software engineering (Python, Docker, Git)"

        - "Machine learning (Scikit-learn, Numpy, PyTorch)"

        - "High performance computing (Shell, Slurm)"

        - "Visualization (Plotly, Bokeh, JavaScript)"

        - "Statistics (R, SciPy, Stan)"

        - "Microbiome data analysis (QIIME2, Pandas)"

  # Experience
  experience:
    enable: true

    items:
      - job: "Data Scientist"
        company: "Napa Oy"
        companyUrl: https://www.napa.fi/
        date: "Mar 2020 - Aug 2020"
        content: |
          Working on the master thesis: "Unsupervised anomaly detection in merchant vessel data"

      - job: "Teaching Assistant"
        company: "Aalto University"
        companyUrl: https://www.aalto.fi/en
        date: "2019 - 2020"
        content: |
          Developing assignments, exams and giving seminars for the follwoing courses:
          - Advanced topics in UI
          - Methods of data mining
          - Machine learning
                    
          Volunteering
            - Ambassador of EIT Digital Academy (2019-2021).

      - job: "Teaching Assistant"
        company: "Eindhoven University of Technology"
        companyUrl: https://www.tue.nl/en/
        date: "2019 - 2020"
        content: |
          Developing assignments, exams and giving seminars for the follwoing courses:
          - Data Modeling
          - Data-Intensive Systems

      - job: "CSP Representative"
        company: "IBM"
        companyUrl: https://www.ibm.com
        date: "Mar 2017 - Aug 2018"
        content: |
          Core responsibilities included:
          - Technical Sales 
          - Prototyping for Cloud Service Providers clients
          - Holding workshops on using IBM Cloud

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "PhD Candidate in Data Science"
        school:
          name: "Helmholtz Munich and LMU, Germany"
          url: https://scholar.google.com/citations?user=ouy_AM4AAAAJ&hl=en
        date: "2021 - now"
        content: |-
          Causal estimation and simulation methods for gut microbiome networks 
          with applications in epidemiology and health.

      - title: "Master in Machine Learning and Big Data Analytics"
        school:
          name: "Aalto University, Finland"
          url: https://www.aalto.fi/en
        date: "2018 - 2020"
        content: |-
          Double-degree programm with focus on:
            - Bayesian Data Analysis.
            - Kernel Methods.
            - Data Visualization.

      - title: "Master in Data Science in Engineering"
        school:
          name: "Eindhoven University of Technology, the Netherlands"
          url: https://www.tue.nl/en/
        date: "2018 - 2020"
        content: |-
          Double-degree programm with focus on:
            - Advanced Algorithms.
            - Statistical Learning Theory.
            - Database Technology.

      - title: "Bachelor of Science in in Business Informatics"
        school:
          name: "National Research University Higher School of Economics"
          url: https://www.hse.ru/en/
        date: "2014 - 2018"
        GPA: "7.98 out of 10"
        content: |
          Major
          - 80% of Computer Science courses
          - 20% of Business and Economics courses
          
          Minor
          - Data Mining
          
          Extracurricular Activities
            - The Chief Executive Officer of HSE Sport Club. 
            - The Chairman of the HSE Student Campus Council.

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: EIT Digital Excellence Scholarship
        content: A merit-based scholarship provided by EIT Digital Academy.
        url: https://www.eitdigital.eu/
      - title: MLH Slash Hackathon
        content: Prize winner with the solution of the air pollution prediction model.
        url: https://www.slash.berlin/
      - title: MLH HackDelft Hackathon
        content: Google prize winner with the cloud computing solution for stock markets.
        url: https://www.facebook.com/hackdelft/

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Food allergy and non-IgE intolerance associations in KORA.
        #content: Data analysis of KORA Cohort for ABROGATE Consortium.
        image: /images/projects/assoc.png
        badges:
          - "Population study"
          - "Causality"
          - "Network analysis"
        links:
          - icon: fa fa-envelope
            url: https://www.helmholtz-munich.de/en/epi/cohort/kora

      - title: Software for solving high-dimensional statistics problems.
        #content: Algorithms for solving General Graphical problems.
        image: /images/projects/q2.png
        featured:
          name: Demo
          link: https://github.com/Vlasovets/q2-gglasso
        badges:
          - "QIIME2"
          - "Open-source"
          - "Optimization theory"
        links:
          - icon: fab fa-github
            url: https://github.com/Vlasovets/q2-gglasso

      - title: Generative modelling of microbial data.
        #content: Data simulation of amplicon sequencing data and associated phenotype information.
        image: /images/projects/GAN.png
#        featured:
#          name: Demo V2
#          link: https://hugo-profile-2.netlify.app
        badges:
          - "GANs"
          - "PyTorch"
          - "Simulation"
#        links:
#          - icon: fab fa-github
#            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: otorrent@mail.ru
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
#
#  footer:
#    recentPosts:
#      path: "blogs"
#      count: 3
#      title: Recent Posts
#      enable: true
#      disableFeaturedImage: false
#    socialNetworks:
#      github: https://github.com
#      linkedin: https://linkedin.com
#      twitter: https://twitter.com
#      medium: https://medium.com/
#
#  # List pages like blogs and posts
#  listPages:
#    disableFeaturedImage: false
#
#  # Single pages like blog and post
#  singlePages:
#    readTime:
#      enable: true
#      content: "min read"
#    scrollprogress:
#      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
